# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, work ]
  pull_request:
    branches: [ master, work ]

env:
  DEBOOTSTRAP_SUITE: buster
  DEBOOTSTRAP_DATE: 2020-08-15


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: $GITHUB_WORKSPACE./cache
          # An explicit key for restoring and saving the cache
          key: cache

      # Runs a set of commands using the runners shell
      - name: Install multi-arch buildx environment
        run: |
          # Install buildx from our container
          docker run --name installbuildx dubodubonduponey/utils /dist/buildx version
          mkdir -p ~/.docker/cli-plugins
          docker cp installbuildx:/dist/buildx ~/.docker/cli-plugins/docker-buildx
          docker rm -f installbuildx
          # Enable multi-arch building
          docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

      - name: hadolint install
        run: |
          curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-$(uname -s)-$(uname -m)"
          chmod 700 ./hadolint

      - name: test
        run: |
          PATH=$PATH:$(pwd)
          cd "$GITHUB_WORKSPACE"
          ./test.sh
